package com.suyh.springboot.dao;

import com.suyh.springboot.entity.CrmContactsInfo;
import java.util.List;

public interface CrmContactsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_contacts_info
     *
     * @mbg.generated
     */
    int insert(CrmContactsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_contacts_info
     *
     * @mbg.generated
     */
    List<CrmContactsInfo> selectAll();
}