package com.suyh.springboot.dao;

import com.suyh.springboot.entity.CrmCustomerInfo;
import java.util.List;

public interface CrmCustomerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_info
     *
     * @mbg.generated
     */
    int insert(CrmCustomerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_info
     *
     * @mbg.generated
     */
    List<CrmCustomerInfo> selectAll();
}