package com.suyh.springboot.dao;

import com.suyh.springboot.entity.CrmPayeeInfo;
import java.util.List;

public interface CrmPayeeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_payee_info
     *
     * @mbg.generated
     */
    int insert(CrmPayeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_payee_info
     *
     * @mbg.generated
     */
    List<CrmPayeeInfo> selectAll();
}