package com.suyh.springboot.dao;

import com.suyh.springboot.entity.CrmSettleMoneyInfo;
import java.util.List;

public interface CrmSettleMoneyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_settle_money_info
     *
     * @mbg.generated
     */
    int insert(CrmSettleMoneyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_settle_money_info
     *
     * @mbg.generated
     */
    List<CrmSettleMoneyInfo> selectAll();
}