package com.suyh.springboot.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table crm_customer_info
 */
public class CrmCustomerInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   主键：客户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_info.customer_id
     *
     * @mbg.generated
     */
    private String customerId;

    /**
     * Database Column Remarks:
     *   客户全称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_info.full_name
     *
     * @mbg.generated
     */
    private String fullName;

    /**
     * Database Column Remarks:
     *   客户简称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_info.short_name
     *
     * @mbg.generated
     */
    private String shortName;

    /**
     * Database Column Remarks:
     *   负责人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_info.manager_name
     *
     * @mbg.generated
     */
    private String managerName;

    /**
     * Database Column Remarks:
     *   联系电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_info.manager_phone
     *
     * @mbg.generated
     */
    private String managerPhone;

    /**
     * Database Column Remarks:
     *   是否内部用户(这个字段似乎有些多余了)【radio:1-是,2-否】
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_info.inner_customer
     *
     * @mbg.generated
     */
    private String innerCustomer;

    /**
     * Database Column Remarks:
     *   客户类型【select:1-内部客户,2-供应商,3-承运商】
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_info.customer_type
     *
     * @mbg.generated
     */
    private String customerType;

    /**
     * Database Column Remarks:
     *   联系地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_info.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   是否使用平台系统(当有自有系统时则可不使用平台系统)【radio:1-是,2-否】
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_info.us_plat_system
     *
     * @mbg.generated
     */
    private String usPlatSystem;

    /**
     * Database Column Remarks:
     *   平台管理员帐号，非自有系统用户才会有。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_info.platform_admin_user
     *
     * @mbg.generated
     */
    private String platformAdminUser;

    /**
     * Database Column Remarks:
     *   启用状态【radio:1-是(启用),2-否(停用)】
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer_info.using_status
     *
     * @mbg.generated
     */
    private String usingStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_customer_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_info.customer_id
     *
     * @return the value of crm_customer_info.customer_id
     *
     * @mbg.generated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_info.customer_id
     *
     * @param customerId the value for crm_customer_info.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_info.full_name
     *
     * @return the value of crm_customer_info.full_name
     *
     * @mbg.generated
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_info.full_name
     *
     * @param fullName the value for crm_customer_info.full_name
     *
     * @mbg.generated
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_info.short_name
     *
     * @return the value of crm_customer_info.short_name
     *
     * @mbg.generated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_info.short_name
     *
     * @param shortName the value for crm_customer_info.short_name
     *
     * @mbg.generated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_info.manager_name
     *
     * @return the value of crm_customer_info.manager_name
     *
     * @mbg.generated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_info.manager_name
     *
     * @param managerName the value for crm_customer_info.manager_name
     *
     * @mbg.generated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_info.manager_phone
     *
     * @return the value of crm_customer_info.manager_phone
     *
     * @mbg.generated
     */
    public String getManagerPhone() {
        return managerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_info.manager_phone
     *
     * @param managerPhone the value for crm_customer_info.manager_phone
     *
     * @mbg.generated
     */
    public void setManagerPhone(String managerPhone) {
        this.managerPhone = managerPhone == null ? null : managerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_info.inner_customer
     *
     * @return the value of crm_customer_info.inner_customer
     *
     * @mbg.generated
     */
    public String getInnerCustomer() {
        return innerCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_info.inner_customer
     *
     * @param innerCustomer the value for crm_customer_info.inner_customer
     *
     * @mbg.generated
     */
    public void setInnerCustomer(String innerCustomer) {
        this.innerCustomer = innerCustomer == null ? null : innerCustomer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_info.customer_type
     *
     * @return the value of crm_customer_info.customer_type
     *
     * @mbg.generated
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_info.customer_type
     *
     * @param customerType the value for crm_customer_info.customer_type
     *
     * @mbg.generated
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType == null ? null : customerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_info.address
     *
     * @return the value of crm_customer_info.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_info.address
     *
     * @param address the value for crm_customer_info.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_info.us_plat_system
     *
     * @return the value of crm_customer_info.us_plat_system
     *
     * @mbg.generated
     */
    public String getUsPlatSystem() {
        return usPlatSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_info.us_plat_system
     *
     * @param usPlatSystem the value for crm_customer_info.us_plat_system
     *
     * @mbg.generated
     */
    public void setUsPlatSystem(String usPlatSystem) {
        this.usPlatSystem = usPlatSystem == null ? null : usPlatSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_info.platform_admin_user
     *
     * @return the value of crm_customer_info.platform_admin_user
     *
     * @mbg.generated
     */
    public String getPlatformAdminUser() {
        return platformAdminUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_info.platform_admin_user
     *
     * @param platformAdminUser the value for crm_customer_info.platform_admin_user
     *
     * @mbg.generated
     */
    public void setPlatformAdminUser(String platformAdminUser) {
        this.platformAdminUser = platformAdminUser == null ? null : platformAdminUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer_info.using_status
     *
     * @return the value of crm_customer_info.using_status
     *
     * @mbg.generated
     */
    public String getUsingStatus() {
        return usingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer_info.using_status
     *
     * @param usingStatus the value for crm_customer_info.using_status
     *
     * @mbg.generated
     */
    public void setUsingStatus(String usingStatus) {
        this.usingStatus = usingStatus == null ? null : usingStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", customerId=").append(customerId);
        sb.append(", fullName=").append(fullName);
        sb.append(", shortName=").append(shortName);
        sb.append(", managerName=").append(managerName);
        sb.append(", managerPhone=").append(managerPhone);
        sb.append(", innerCustomer=").append(innerCustomer);
        sb.append(", customerType=").append(customerType);
        sb.append(", address=").append(address);
        sb.append(", usPlatSystem=").append(usPlatSystem);
        sb.append(", platformAdminUser=").append(platformAdminUser);
        sb.append(", usingStatus=").append(usingStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}