package com.suyh.springboot.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table crm_contacts_info
 */
public class CrmContactsInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   主键ID: 联系人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_contacts_info.contacts_id
     *
     * @mbg.generated
     */
    private String contactsId;

    /**
     * Database Column Remarks:
     *   属主ID，映射到客户基本信息表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_contacts_info.customer_id
     *
     * @mbg.generated
     */
    private String customerId;

    /**
     * Database Column Remarks:
     *   联系类别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_contacts_info.contacts_kinds
     *
     * @mbg.generated
     */
    private String contactsKinds;

    /**
     * Database Column Remarks:
     *   联系人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_contacts_info.contacts_name
     *
     * @mbg.generated
     */
    private String contactsName;

    /**
     * Database Column Remarks:
     *   电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_contacts_info.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_contacts_info.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   QQ 号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_contacts_info.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     * Database Column Remarks:
     *   微信
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_contacts_info.wechat
     *
     * @mbg.generated
     */
    private String wechat;

    /**
     * Database Column Remarks:
     *   地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_contacts_info.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_contacts_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contacts_info.contacts_id
     *
     * @return the value of crm_contacts_info.contacts_id
     *
     * @mbg.generated
     */
    public String getContactsId() {
        return contactsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contacts_info.contacts_id
     *
     * @param contactsId the value for crm_contacts_info.contacts_id
     *
     * @mbg.generated
     */
    public void setContactsId(String contactsId) {
        this.contactsId = contactsId == null ? null : contactsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contacts_info.customer_id
     *
     * @return the value of crm_contacts_info.customer_id
     *
     * @mbg.generated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contacts_info.customer_id
     *
     * @param customerId the value for crm_contacts_info.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contacts_info.contacts_kinds
     *
     * @return the value of crm_contacts_info.contacts_kinds
     *
     * @mbg.generated
     */
    public String getContactsKinds() {
        return contactsKinds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contacts_info.contacts_kinds
     *
     * @param contactsKinds the value for crm_contacts_info.contacts_kinds
     *
     * @mbg.generated
     */
    public void setContactsKinds(String contactsKinds) {
        this.contactsKinds = contactsKinds == null ? null : contactsKinds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contacts_info.contacts_name
     *
     * @return the value of crm_contacts_info.contacts_name
     *
     * @mbg.generated
     */
    public String getContactsName() {
        return contactsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contacts_info.contacts_name
     *
     * @param contactsName the value for crm_contacts_info.contacts_name
     *
     * @mbg.generated
     */
    public void setContactsName(String contactsName) {
        this.contactsName = contactsName == null ? null : contactsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contacts_info.phone
     *
     * @return the value of crm_contacts_info.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contacts_info.phone
     *
     * @param phone the value for crm_contacts_info.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contacts_info.email
     *
     * @return the value of crm_contacts_info.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contacts_info.email
     *
     * @param email the value for crm_contacts_info.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contacts_info.qq
     *
     * @return the value of crm_contacts_info.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contacts_info.qq
     *
     * @param qq the value for crm_contacts_info.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contacts_info.wechat
     *
     * @return the value of crm_contacts_info.wechat
     *
     * @mbg.generated
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contacts_info.wechat
     *
     * @param wechat the value for crm_contacts_info.wechat
     *
     * @mbg.generated
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contacts_info.address
     *
     * @return the value of crm_contacts_info.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contacts_info.address
     *
     * @param address the value for crm_contacts_info.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_contacts_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", contactsId=").append(contactsId);
        sb.append(", customerId=").append(customerId);
        sb.append(", contactsKinds=").append(contactsKinds);
        sb.append(", contactsName=").append(contactsName);
        sb.append(", phone=").append(phone);
        sb.append(", email=").append(email);
        sb.append(", qq=").append(qq);
        sb.append(", wechat=").append(wechat);
        sb.append(", address=").append(address);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}