package com.suyh.springboot.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table crm_invoice_info
 */
public class CrmInvoiceInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   主键ID：发票信息ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_invoice_info.invoice_info_id
     *
     * @mbg.generated
     */
    private String invoiceInfoId;

    /**
     * Database Column Remarks:
     *   属主ID，映射到客户基本信息表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_invoice_info.customer_id
     *
     * @mbg.generated
     */
    private String customerId;

    /**
     * Database Column Remarks:
     *   发票类型【select:1-增值税普通发票（电子）,2-增值税普通发票（纸制）3-增值税专用发票,...(其他)】
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_invoice_info.invoice_type_id
     *
     * @mbg.generated
     */
    private String invoiceTypeId;

    /**
     * Database Column Remarks:
     *   受票方名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_invoice_info.drawee_name
     *
     * @mbg.generated
     */
    private String draweeName;

    /**
     * Database Column Remarks:
     *   统一社会信息代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_invoice_info.unified_social_credit_code
     *
     * @mbg.generated
     */
    private String unifiedSocialCreditCode;

    /**
     * Database Column Remarks:
     *   开户行名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_invoice_info.opening_bank
     *
     * @mbg.generated
     */
    private String openingBank;

    /**
     * Database Column Remarks:
     *   注册电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_invoice_info.register_phone
     *
     * @mbg.generated
     */
    private String registerPhone;

    /**
     * Database Column Remarks:
     *   银行帐号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_invoice_info.bank_account_code
     *
     * @mbg.generated
     */
    private String bankAccountCode;

    /**
     * Database Column Remarks:
     *   帐户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_invoice_info.bank_account_name
     *
     * @mbg.generated
     */
    private String bankAccountName;

    /**
     * Database Column Remarks:
     *   注册地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_invoice_info.register_address
     *
     * @mbg.generated
     */
    private String registerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_invoice_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_invoice_info.invoice_info_id
     *
     * @return the value of crm_invoice_info.invoice_info_id
     *
     * @mbg.generated
     */
    public String getInvoiceInfoId() {
        return invoiceInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_invoice_info.invoice_info_id
     *
     * @param invoiceInfoId the value for crm_invoice_info.invoice_info_id
     *
     * @mbg.generated
     */
    public void setInvoiceInfoId(String invoiceInfoId) {
        this.invoiceInfoId = invoiceInfoId == null ? null : invoiceInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_invoice_info.customer_id
     *
     * @return the value of crm_invoice_info.customer_id
     *
     * @mbg.generated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_invoice_info.customer_id
     *
     * @param customerId the value for crm_invoice_info.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_invoice_info.invoice_type_id
     *
     * @return the value of crm_invoice_info.invoice_type_id
     *
     * @mbg.generated
     */
    public String getInvoiceTypeId() {
        return invoiceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_invoice_info.invoice_type_id
     *
     * @param invoiceTypeId the value for crm_invoice_info.invoice_type_id
     *
     * @mbg.generated
     */
    public void setInvoiceTypeId(String invoiceTypeId) {
        this.invoiceTypeId = invoiceTypeId == null ? null : invoiceTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_invoice_info.drawee_name
     *
     * @return the value of crm_invoice_info.drawee_name
     *
     * @mbg.generated
     */
    public String getDraweeName() {
        return draweeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_invoice_info.drawee_name
     *
     * @param draweeName the value for crm_invoice_info.drawee_name
     *
     * @mbg.generated
     */
    public void setDraweeName(String draweeName) {
        this.draweeName = draweeName == null ? null : draweeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_invoice_info.unified_social_credit_code
     *
     * @return the value of crm_invoice_info.unified_social_credit_code
     *
     * @mbg.generated
     */
    public String getUnifiedSocialCreditCode() {
        return unifiedSocialCreditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_invoice_info.unified_social_credit_code
     *
     * @param unifiedSocialCreditCode the value for crm_invoice_info.unified_social_credit_code
     *
     * @mbg.generated
     */
    public void setUnifiedSocialCreditCode(String unifiedSocialCreditCode) {
        this.unifiedSocialCreditCode = unifiedSocialCreditCode == null ? null : unifiedSocialCreditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_invoice_info.opening_bank
     *
     * @return the value of crm_invoice_info.opening_bank
     *
     * @mbg.generated
     */
    public String getOpeningBank() {
        return openingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_invoice_info.opening_bank
     *
     * @param openingBank the value for crm_invoice_info.opening_bank
     *
     * @mbg.generated
     */
    public void setOpeningBank(String openingBank) {
        this.openingBank = openingBank == null ? null : openingBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_invoice_info.register_phone
     *
     * @return the value of crm_invoice_info.register_phone
     *
     * @mbg.generated
     */
    public String getRegisterPhone() {
        return registerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_invoice_info.register_phone
     *
     * @param registerPhone the value for crm_invoice_info.register_phone
     *
     * @mbg.generated
     */
    public void setRegisterPhone(String registerPhone) {
        this.registerPhone = registerPhone == null ? null : registerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_invoice_info.bank_account_code
     *
     * @return the value of crm_invoice_info.bank_account_code
     *
     * @mbg.generated
     */
    public String getBankAccountCode() {
        return bankAccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_invoice_info.bank_account_code
     *
     * @param bankAccountCode the value for crm_invoice_info.bank_account_code
     *
     * @mbg.generated
     */
    public void setBankAccountCode(String bankAccountCode) {
        this.bankAccountCode = bankAccountCode == null ? null : bankAccountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_invoice_info.bank_account_name
     *
     * @return the value of crm_invoice_info.bank_account_name
     *
     * @mbg.generated
     */
    public String getBankAccountName() {
        return bankAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_invoice_info.bank_account_name
     *
     * @param bankAccountName the value for crm_invoice_info.bank_account_name
     *
     * @mbg.generated
     */
    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName == null ? null : bankAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_invoice_info.register_address
     *
     * @return the value of crm_invoice_info.register_address
     *
     * @mbg.generated
     */
    public String getRegisterAddress() {
        return registerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_invoice_info.register_address
     *
     * @param registerAddress the value for crm_invoice_info.register_address
     *
     * @mbg.generated
     */
    public void setRegisterAddress(String registerAddress) {
        this.registerAddress = registerAddress == null ? null : registerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_invoice_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", invoiceInfoId=").append(invoiceInfoId);
        sb.append(", customerId=").append(customerId);
        sb.append(", invoiceTypeId=").append(invoiceTypeId);
        sb.append(", draweeName=").append(draweeName);
        sb.append(", unifiedSocialCreditCode=").append(unifiedSocialCreditCode);
        sb.append(", openingBank=").append(openingBank);
        sb.append(", registerPhone=").append(registerPhone);
        sb.append(", bankAccountCode=").append(bankAccountCode);
        sb.append(", bankAccountName=").append(bankAccountName);
        sb.append(", registerAddress=").append(registerAddress);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}