package com.suyh.springboot.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table crm_payee_info
 */
public class CrmPayeeInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   主键ID：收款人信息ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_payee_info.payee_info_id
     *
     * @mbg.generated
     */
    private String payeeInfoId;

    /**
     * Database Column Remarks:
     *   属主ID，映射到客户基本信息表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_payee_info.customer_id
     *
     * @mbg.generated
     */
    private String customerId;

    /**
     * Database Column Remarks:
     *   开户行名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_payee_info.opening_bank
     *
     * @mbg.generated
     */
    private String openingBank;

    /**
     * Database Column Remarks:
     *   银行帐号-收款帐户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_payee_info.bank_account_code
     *
     * @mbg.generated
     */
    private String bankAccountCode;

    /**
     * Database Column Remarks:
     *   帐户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_payee_info.bank_account_name
     *
     * @mbg.generated
     */
    private String bankAccountName;

    /**
     * Database Column Remarks:
     *   操作人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_payee_info.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_payee_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_payee_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_payee_info.payee_info_id
     *
     * @return the value of crm_payee_info.payee_info_id
     *
     * @mbg.generated
     */
    public String getPayeeInfoId() {
        return payeeInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_payee_info.payee_info_id
     *
     * @param payeeInfoId the value for crm_payee_info.payee_info_id
     *
     * @mbg.generated
     */
    public void setPayeeInfoId(String payeeInfoId) {
        this.payeeInfoId = payeeInfoId == null ? null : payeeInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_payee_info.customer_id
     *
     * @return the value of crm_payee_info.customer_id
     *
     * @mbg.generated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_payee_info.customer_id
     *
     * @param customerId the value for crm_payee_info.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_payee_info.opening_bank
     *
     * @return the value of crm_payee_info.opening_bank
     *
     * @mbg.generated
     */
    public String getOpeningBank() {
        return openingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_payee_info.opening_bank
     *
     * @param openingBank the value for crm_payee_info.opening_bank
     *
     * @mbg.generated
     */
    public void setOpeningBank(String openingBank) {
        this.openingBank = openingBank == null ? null : openingBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_payee_info.bank_account_code
     *
     * @return the value of crm_payee_info.bank_account_code
     *
     * @mbg.generated
     */
    public String getBankAccountCode() {
        return bankAccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_payee_info.bank_account_code
     *
     * @param bankAccountCode the value for crm_payee_info.bank_account_code
     *
     * @mbg.generated
     */
    public void setBankAccountCode(String bankAccountCode) {
        this.bankAccountCode = bankAccountCode == null ? null : bankAccountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_payee_info.bank_account_name
     *
     * @return the value of crm_payee_info.bank_account_name
     *
     * @mbg.generated
     */
    public String getBankAccountName() {
        return bankAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_payee_info.bank_account_name
     *
     * @param bankAccountName the value for crm_payee_info.bank_account_name
     *
     * @mbg.generated
     */
    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName == null ? null : bankAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_payee_info.operator
     *
     * @return the value of crm_payee_info.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_payee_info.operator
     *
     * @param operator the value for crm_payee_info.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_payee_info.update_time
     *
     * @return the value of crm_payee_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_payee_info.update_time
     *
     * @param updateTime the value for crm_payee_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_payee_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", payeeInfoId=").append(payeeInfoId);
        sb.append(", customerId=").append(customerId);
        sb.append(", openingBank=").append(openingBank);
        sb.append(", bankAccountCode=").append(bankAccountCode);
        sb.append(", bankAccountName=").append(bankAccountName);
        sb.append(", operator=").append(operator);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}