package com.suyh.springboot.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table crm_settle_money_info
 */
public class CrmSettleMoneyInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   主键：映射到客户基础信息表客户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_settle_money_info.customer_id
     *
     * @mbg.generated
     */
    private String customerId;

    /**
     * Database Column Remarks:
     *   结算方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_settle_money_info.settle_type
     *
     * @mbg.generated
     */
    private String settleType;

    /**
     * Database Column Remarks:
     *   月结日，以0 表示自然月
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_settle_money_info.settle_day
     *
     * @mbg.generated
     */
    private Integer settleDay;

    /**
     * Database Column Remarks:
     *   开票税点(%)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_settle_money_info.tax_rate
     *
     * @mbg.generated
     */
    private String taxRate;

    /**
     * Database Column Remarks:
     *   允许延期天数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_settle_money_info.enable_delay_days
     *
     * @mbg.generated
     */
    private Integer enableDelayDays;

    /**
     * Database Column Remarks:
     *   欠款上限(元)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_settle_money_info.max_arrears_money
     *
     * @mbg.generated
     */
    private Integer maxArrearsMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_settle_money_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_settle_money_info.customer_id
     *
     * @return the value of crm_settle_money_info.customer_id
     *
     * @mbg.generated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_settle_money_info.customer_id
     *
     * @param customerId the value for crm_settle_money_info.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_settle_money_info.settle_type
     *
     * @return the value of crm_settle_money_info.settle_type
     *
     * @mbg.generated
     */
    public String getSettleType() {
        return settleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_settle_money_info.settle_type
     *
     * @param settleType the value for crm_settle_money_info.settle_type
     *
     * @mbg.generated
     */
    public void setSettleType(String settleType) {
        this.settleType = settleType == null ? null : settleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_settle_money_info.settle_day
     *
     * @return the value of crm_settle_money_info.settle_day
     *
     * @mbg.generated
     */
    public Integer getSettleDay() {
        return settleDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_settle_money_info.settle_day
     *
     * @param settleDay the value for crm_settle_money_info.settle_day
     *
     * @mbg.generated
     */
    public void setSettleDay(Integer settleDay) {
        this.settleDay = settleDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_settle_money_info.tax_rate
     *
     * @return the value of crm_settle_money_info.tax_rate
     *
     * @mbg.generated
     */
    public String getTaxRate() {
        return taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_settle_money_info.tax_rate
     *
     * @param taxRate the value for crm_settle_money_info.tax_rate
     *
     * @mbg.generated
     */
    public void setTaxRate(String taxRate) {
        this.taxRate = taxRate == null ? null : taxRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_settle_money_info.enable_delay_days
     *
     * @return the value of crm_settle_money_info.enable_delay_days
     *
     * @mbg.generated
     */
    public Integer getEnableDelayDays() {
        return enableDelayDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_settle_money_info.enable_delay_days
     *
     * @param enableDelayDays the value for crm_settle_money_info.enable_delay_days
     *
     * @mbg.generated
     */
    public void setEnableDelayDays(Integer enableDelayDays) {
        this.enableDelayDays = enableDelayDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_settle_money_info.max_arrears_money
     *
     * @return the value of crm_settle_money_info.max_arrears_money
     *
     * @mbg.generated
     */
    public Integer getMaxArrearsMoney() {
        return maxArrearsMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_settle_money_info.max_arrears_money
     *
     * @param maxArrearsMoney the value for crm_settle_money_info.max_arrears_money
     *
     * @mbg.generated
     */
    public void setMaxArrearsMoney(Integer maxArrearsMoney) {
        this.maxArrearsMoney = maxArrearsMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_settle_money_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", customerId=").append(customerId);
        sb.append(", settleType=").append(settleType);
        sb.append(", settleDay=").append(settleDay);
        sb.append(", taxRate=").append(taxRate);
        sb.append(", enableDelayDays=").append(enableDelayDays);
        sb.append(", maxArrearsMoney=").append(maxArrearsMoney);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}